/**
 * CSS custom properties — drop-in `:root { --* }` declarations plus a
 * Tailwind-v4-compatible `@theme` block.
 */
import type { Artifact, CanonicalExtraction } from '@prism/shared';
import { textArtifact } from './artifact.js';
import { colorCss, keyedTokens, lengthCss, radiusCss, shadowCss, tokensByCategory, typographyCss } from './shared.js';

export function generateCssVariables(extraction: CanonicalExtraction): Artifact {
  const t = tokensByCategory(extraction);
  const sections: string[] = [];

  const push = (title: string, lines: string[]) => {
    if (lines.length === 0) return;
    sections.push(`  /* ${title} */\n${lines.map((l) => `  ${l}`).join('\n')}`);
  };

  push(
    'Colors',
    keyedTokens(t.colors).map(({ key, value }) => `--color-${key}: ${colorCss(value.value)};`),
  );
  push(
    'Typography families',
    keyedTokens(t.typography).map(({ key, value }) => {
      const v = typographyCss(value);
      return `--font-${key}: ${v.family};`;
    }),
  );
  push(
    'Typography sizes',
    keyedTokens(t.typography).map(({ key, value }) => {
      const v = typographyCss(value);
      return `--text-${key}: ${v.size};`;
    }),
  );
  push(
    'Spacing',
    keyedTokens(t.spacing).map(({ key, value }) => `--space-${key}: ${lengthCss(value.value)};`),
  );
  push(
    'Radii',
    keyedTokens(t.radii).map(({ key, value }) => `--radius-${key}: ${radiusCss(value)};`),
  );
  push(
    'Shadows',
    keyedTokens(t.shadows).map(({ key, value }) => `--shadow-${key}: ${shadowCss(value)};`),
  );

  const body = sections.join('\n\n');
  const text = [
    `/* Generated by Prism — https://github.com/REPLACE_ME/prism */`,
    `/* Extraction ${extraction.extractionId} · ${extraction.tokens.length} tokens */`,
    ``,
    `:root {`,
    body,
    `}`,
    ``,
  ].join('\n');

  return textArtifact({
    format: 'css-variables',
    filename: 'tokens.css',
    contentType: 'text/css',
    text,
  });
}
