/**
 * CSS-in-JS token object — works with Emotion, styled-components, and any
 * JS/TS runtime. Emits a typed `as const` export so IDEs autocomplete.
 */
import type { Artifact, CanonicalExtraction } from '@prism/shared';
import { textArtifact } from './artifact.js';
import { colorCss, keyedTokens, lengthCss, radiusCss, shadowCss, tokensByCategory, typographyCss } from './shared.js';

function quoted(value: string): string {
  return `'${value.replace(/'/g, "\\'")}'`;
}

function object(entries: { key: string; value: string }[], indent = '    '): string {
  if (entries.length === 0) return '{}';
  const lines = entries.map(({ key, value }) => `${indent}${quoted(key)}: ${value},`);
  return `{\n${lines.join('\n')}\n${indent.slice(2)}}`;
}

export function generateCssInJs(extraction: CanonicalExtraction): Artifact {
  const t = tokensByCategory(extraction);

  const colors = keyedTokens(t.colors).map(({ key, value }) => ({
    key,
    value: quoted(colorCss(value.value)),
  }));
  const spacing = keyedTokens(t.spacing).map(({ key, value }) => ({
    key,
    value: quoted(lengthCss(value.value)),
  }));
  const radii = keyedTokens(t.radii).map(({ key, value }) => ({
    key,
    value: quoted(radiusCss(value)),
  }));
  const shadows = keyedTokens(t.shadows).map(({ key, value }) => ({
    key,
    value: quoted(shadowCss(value)),
  }));

  const typography = keyedTokens(t.typography).map(({ key, value }) => {
    const v = typographyCss(value);
    const props: string[] = [
      `      fontFamily: ${quoted(v.family)}`,
      `      fontSize: ${quoted(v.size)}`,
      `      fontWeight: ${v.weight}`,
    ];
    if (v.lineHeight !== undefined) props.push(`      lineHeight: ${quoted(v.lineHeight)}`);
    if (v.letterSpacing !== undefined) props.push(`      letterSpacing: ${quoted(v.letterSpacing)}`);
    return { key, value: `{\n${props.join(',\n')},\n    }` };
  });

  const text = [
    `/* Generated by Prism — https://github.com/REPLACE_ME/prism */`,
    `/* Extraction ${extraction.extractionId} · ${extraction.tokens.length} tokens */`,
    ``,
    `export const tokens = {`,
    `  colors: ${object(colors)},`,
    `  spacing: ${object(spacing)},`,
    `  radii: ${object(radii)},`,
    `  shadows: ${object(shadows)},`,
    `  typography: ${object(typography)},`,
    `} as const;`,
    ``,
    `export type Tokens = typeof tokens;`,
    ``,
  ].join('\n');

  return textArtifact({
    format: 'css-in-js',
    filename: 'tokens.ts',
    contentType: 'application/typescript',
    text,
  });
}
