import JSZip from 'jszip';
import { describe, expect, it } from 'vitest';
import { fixtureExtraction } from './fixture.js';
import { generate, generateAll, SUPPORTED_FORMATS_V1 } from './index.js';

describe('generate()', () => {
  it('produces an Artifact for every supported format', async () => {
    const extraction = fixtureExtraction();
    for (const format of SUPPORTED_FORMATS_V1) {
      const artifact = await generate(extraction, format);
      expect(artifact.format).toBe(format);
      expect(artifact.hash).toMatch(/^[0-9a-f]{64}$/);
      expect(artifact.sizeBytes).toBeGreaterThan(0);
      expect(['text', 'bytes']).toContain(artifact.content.kind);
    }
  });

  it('generateAll() returns one artifact per supported format', async () => {
    const artifacts = await generateAll(fixtureExtraction());
    expect(artifacts).toHaveLength(SUPPORTED_FORMATS_V1.length);
  });
});

describe('design-tokens-json', () => {
  it('produces valid DTCG with semantic roles as leaf keys', async () => {
    const artifact = await generate(fixtureExtraction(), 'design-tokens-json');
    if (artifact.content.kind !== 'text') throw new Error('expected text');
    const tree = JSON.parse(artifact.content.text) as Record<string, unknown>;
    expect(tree.color).toBeDefined();
    const colorGroup = tree.color as Record<string, { $value: string; $type: string }>;
    expect(colorGroup.primary?.$value).toBe('#3b82f6');
    expect(colorGroup.primary?.$type).toBe('color');
    const spacingGroup = tree.spacing as Record<string, { $value: string }>;
    expect(spacingGroup['space-16']?.$value).toBe('16px');
  });
});

describe('tailwind-config', () => {
  it('generates compilable tailwind.config.ts with our tokens', async () => {
    const artifact = await generate(fixtureExtraction(), 'tailwind-config');
    if (artifact.content.kind !== 'text') throw new Error('expected text');
    const src = artifact.content.text;
    expect(src).toContain(`import type { Config } from 'tailwindcss'`);
    expect(src).toContain(`'primary': '#3b82f6'`);
    expect(src).toContain(`'background': '#ffffff'`);
    expect(src).toContain(`fontFamily:`);
    expect(src).toContain(`'Inter'`);
    expect(src).toContain(`boxShadow:`);
    expect(src).toContain(`satisfies Config`);
  });
});

describe('css-variables', () => {
  it('emits :root with prefixed custom properties', async () => {
    const artifact = await generate(fixtureExtraction(), 'css-variables');
    if (artifact.content.kind !== 'text') throw new Error('expected text');
    const css = artifact.content.text;
    expect(css).toMatch(/--color-primary:\s*#3b82f6;/);
    expect(css).toMatch(/--space-space-16:\s*16px;/);
    expect(css).toMatch(/--radius-radius-4:\s*4px;/);
    expect(css.startsWith('/* Generated by Prism')).toBe(true);
  });
});

describe('scss', () => {
  it('emits one $-map per category', async () => {
    const artifact = await generate(fixtureExtraction(), 'scss');
    if (artifact.content.kind !== 'text') throw new Error('expected text');
    const src = artifact.content.text;
    expect(src).toContain('$colors: (');
    expect(src).toContain('"primary": #3b82f6,');
    expect(src).toContain('$spacing: (');
    expect(src).toContain('$radii: (');
  });
});

describe('css-in-js', () => {
  it('emits a typed `as const` export', async () => {
    const artifact = await generate(fixtureExtraction(), 'css-in-js');
    if (artifact.content.kind !== 'text') throw new Error('expected text');
    const src = artifact.content.text;
    expect(src).toContain('export const tokens = {');
    expect(src).toContain(`'primary': '#3b82f6'`);
    expect(src).toContain(`'space-16': '16px'`);
    expect(src).toContain('} as const;');
    expect(src).toContain('export type Tokens = typeof tokens;');
  });
});

describe('design-md-compact', () => {
  it('produces a markdown summary with key sections', async () => {
    const artifact = await generate(fixtureExtraction(), 'design-md-compact');
    if (artifact.content.kind !== 'text') throw new Error('expected text');
    const md = artifact.content.text;
    expect(md).toMatch(/^# Design System$/m);
    expect(md).toContain('## Colors (4)');
    expect(md).toContain('## Typography (3)');
    expect(md).toContain('## Spacing');
    expect(md).toContain('4px scale detected');
    expect(md).toContain('## Radii (2)');
    expect(md).toContain('## Shadows (1)');
    expect(md).toContain('`#3b82f6`');
  });

  it('stays under 32 KB for the fixture (compact budget sanity)', async () => {
    const artifact = await generate(fixtureExtraction(), 'design-md-compact');
    expect(artifact.sizeBytes).toBeLessThan(32 * 1024);
  });
});

describe('design-md-extended', () => {
  it('includes evidence, cost breakdown, and run summary', async () => {
    const artifact = await generate(fixtureExtraction(), 'design-md-extended');
    if (artifact.content.kind !== 'text') throw new Error('expected text');
    const md = artifact.content.text;
    expect(md).toContain('# Design System (extended)');
    expect(md).toContain('## Run summary');
    expect(md).toContain('**Cost:**');
    expect(md).toContain('## Model calls');
    expect(md).toContain('claude-sonnet-4-6');
    expect(md).toContain('_Evidence');
  });
});

describe('figma-tokens-json', () => {
  it('emits Tokens Studio-shaped tree', async () => {
    const artifact = await generate(fixtureExtraction(), 'figma-tokens-json');
    if (artifact.content.kind !== 'text') throw new Error('expected text');
    const tree = JSON.parse(artifact.content.text) as {
      global: Record<string, Record<string, { value: unknown; type: string }>>;
      $themes: unknown[];
      $metadata: { tokenSetOrder: string[] };
    };
    expect(tree.$metadata.tokenSetOrder).toEqual(['global']);
    expect(tree.global.color?.primary?.value).toBe('#3b82f6');
    expect(tree.global.color?.primary?.type).toBe('color');
    expect(tree.global.spacing?.['space-16']?.value).toBe('16');
    expect(tree.global.spacing?.['space-16']?.type).toBe('spacing');
  });
});

describe('style-dictionary-config', () => {
  it('emits a multi-platform config pointing at design-tokens.json', async () => {
    const artifact = await generate(fixtureExtraction(), 'style-dictionary-config');
    if (artifact.content.kind !== 'text') throw new Error('expected text');
    const config = JSON.parse(artifact.content.text) as {
      source: string[];
      platforms: Record<string, unknown>;
    };
    expect(config.source).toContain('design-tokens.json');
    expect(Object.keys(config.platforms)).toEqual(
      expect.arrayContaining(['css', 'scss', 'js', 'ios', 'android']),
    );
  });
});

describe('storybook-stories', () => {
  it('returns a ZIP with a stories folder and README (stub for no components)', async () => {
    const artifact = await generate(fixtureExtraction(), 'storybook-stories');
    if (artifact.content.kind !== 'bytes') throw new Error('expected bytes');
    const zip = await JSZip.loadAsync(Buffer.from(artifact.content.bytesBase64, 'base64'));
    expect(zip.file('stories/README.md')).not.toBeNull();
  });
});

describe('react-component-scaffolds', () => {
  it('returns a ZIP with a components folder and README', async () => {
    const artifact = await generate(fixtureExtraction(), 'react-component-scaffolds');
    if (artifact.content.kind !== 'bytes') throw new Error('expected bytes');
    const zip = await JSZip.loadAsync(Buffer.from(artifact.content.bytesBase64, 'base64'));
    expect(zip.file('components/README.md')).not.toBeNull();
  });
});

describe('asset-bundle-zip', () => {
  it('returns a ZIP with manifest.json', async () => {
    const artifact = await generate(fixtureExtraction(), 'asset-bundle-zip');
    if (artifact.content.kind !== 'bytes') throw new Error('expected bytes');
    const zip = await JSZip.loadAsync(Buffer.from(artifact.content.bytesBase64, 'base64'));
    const manifest = await zip.file('manifest.json')?.async('string');
    expect(manifest).toBeDefined();
    const parsed = JSON.parse(manifest!) as { assetCount: number; assets: unknown[] };
    expect(parsed.assetCount).toBe(0); // fixture has no assets
  });
});

describe('docs-site-zip', () => {
  it('returns a ZIP with index.html + tokens.css', async () => {
    const artifact = await generate(fixtureExtraction(), 'docs-site-zip');
    if (artifact.content.kind !== 'bytes') throw new Error('expected bytes');
    const zip = await JSZip.loadAsync(Buffer.from(artifact.content.bytesBase64, 'base64'));
    const html = await zip.file('index.html')?.async('string');
    expect(html).toContain('<h1>Design System</h1>');
    expect(html).toContain('#3b82f6');
    expect(zip.file('tokens.css')).not.toBeNull();
  });
});

describe('artifact envelope', () => {
  it('gives the same hash for identical extractions', async () => {
    const a = await generate(fixtureExtraction(), 'design-tokens-json');
    const b = await generate(fixtureExtraction(), 'design-tokens-json');
    expect(a.hash).toBe(b.hash);
  });
});
