/**
 * React component scaffolds. Experimental — these are starting points, not
 * production-ready components. Each detected component gets a TSX file with
 * its variants as a `variant` prop, plus inferred prop signatures.
 *
 * Clearly marked experimental in the README inside the ZIP so users don't
 * ship generated code unreviewed.
 */
import JSZip from 'jszip';
import type {
  Artifact,
  CanonicalExtraction,
  Component,
  PropSignature,
} from '@prism/shared';
import { bytesArtifact } from './artifact.js';

function toPascalCase(input: string): string {
  return input
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .trim()
    .split(/\s+/)
    .map((w) => (w ? w[0]!.toUpperCase() + w.slice(1).toLowerCase() : ''))
    .join('');
}

function renderPropsType(name: string, props: PropSignature[]): string {
  const lines = props.map((p) => {
    const optional = p.required ? '' : '?';
    const type =
      p.options.length > 0
        ? p.options.map((o) => `'${o.replace(/'/g, "\\'")}'`).join(' | ')
        : p.kind === 'boolean'
          ? 'boolean'
          : p.kind === 'children'
            ? 'React.ReactNode'
            : 'string';
    return `  ${p.name}${optional}: ${type};`;
  });
  return `export interface ${name}Props {\n${lines.join('\n')}\n}`;
}

function renderComponent(component: Component): string {
  const pascalName = toPascalCase(component.name);
  const variants = component.variants.map((v) => v.name);
  const hasVariants = variants.length > 0;
  const propsType =
    component.props.length > 0 ? renderPropsType(pascalName, component.props) : '';

  const variantUnion = hasVariants
    ? variants.map((v) => `'${v.replace(/'/g, "\\'")}'`).join(' | ')
    : 'string';

  return `/**
 * Auto-generated by Prism. EXPERIMENTAL — review before shipping.
 * Detected as "${component.kind}" (confidence ${component.confidence.toFixed(2)}).
 * ${hasVariants ? `Variants: ${variants.join(', ')}.` : 'No variants detected.'}
 */
import * as React from 'react';

${propsType}

${
  hasVariants
    ? `type ${pascalName}Variant = ${variantUnion};\n`
    : ''
}
export function ${pascalName}(${
    component.props.length > 0
      ? `props: ${pascalName}Props & React.HTMLAttributes<HTMLDivElement>${
          hasVariants ? ` & { variant?: ${pascalName}Variant }` : ''
        }`
      : `props: React.HTMLAttributes<HTMLDivElement>${
          hasVariants ? ` & { variant?: ${pascalName}Variant }` : ''
        }`
  }): JSX.Element {
  // TODO: replace this with the actual component implementation.
  return <div data-prism-component="${component.kind}" {...props} />;
}
`;
}

function readme(componentCount: number): string {
  return `# Prism React scaffolds (experimental)

> ⚠️ **Experimental output.** These files are starting points generated from
> detected components. They do NOT implement the visual behavior — they scaffold
> the TypeScript surface. Review + adapt before shipping.

${componentCount} component(s) detected.

## Using these

1. Drop the \`components/\` folder into your project.
2. Wire up each component's implementation using the Prism-generated token
   files (\`tokens.css\`, \`tailwind.config.ts\`, or \`tokens.ts\`).
3. Delete this README once you've reviewed.

## Safety

Prism will never ship "done" React code; the vision model's component detection
is best treated as a hinting layer, not the source of truth. Treat every
generated file as a pull-request suggestion.
`;
}

export async function generateReactScaffolds(
  extraction: CanonicalExtraction,
): Promise<Artifact> {
  const zip = new JSZip();
  const components = zip.folder('components');
  if (!components) throw new Error('jszip folder creation failed');

  if (extraction.components.length === 0) {
    components.file('README.md', readme(0));
  } else {
    const seen = new Set<string>();
    for (const c of extraction.components) {
      let pascal = toPascalCase(c.name);
      if (seen.has(pascal)) {
        let n = 2;
        while (seen.has(`${pascal}${n}`)) n++;
        pascal = `${pascal}${n}`;
      }
      seen.add(pascal);
      const safeComponent = { ...c, name: pascal };
      components.file(`${pascal}.tsx`, renderComponent(safeComponent));
    }
    components.file('README.md', readme(extraction.components.length));
  }

  const bytes = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' });
  return bytesArtifact({
    format: 'react-component-scaffolds',
    filename: 'react-scaffolds.zip',
    contentType: 'application/zip',
    bytes,
  });
}
