/**
 * SCSS $-maps — one map per category.
 */
import type { Artifact, CanonicalExtraction } from '@prism/shared';
import { textArtifact } from './artifact.js';
import { colorCss, keyedTokens, lengthCss, radiusCss, shadowCss, tokensByCategory, typographyCss } from './shared.js';

function mapOf<T>(name: string, entries: { key: string; value: string }[]): string {
  if (entries.length === 0) return '';
  const lines = entries.map(({ key, value }) => `  "${key}": ${value},`);
  return `$${name}: (\n${lines.join('\n')}\n);\n`;
}

export function generateScss(extraction: CanonicalExtraction): Artifact {
  const t = tokensByCategory(extraction);
  const pieces: string[] = [
    `// Generated by Prism — https://github.com/REPLACE_ME/prism`,
    `// Extraction ${extraction.extractionId} · ${extraction.tokens.length} tokens`,
    ``,
  ];

  const colors = keyedTokens(t.colors).map(({ key, value }) => ({
    key,
    value: colorCss(value.value),
  }));
  pieces.push(mapOf('colors', colors));

  const spacing = keyedTokens(t.spacing).map(({ key, value }) => ({
    key,
    value: lengthCss(value.value),
  }));
  pieces.push(mapOf('spacing', spacing));

  const radii = keyedTokens(t.radii).map(({ key, value }) => ({ key, value: radiusCss(value) }));
  pieces.push(mapOf('radii', radii));

  const shadows = keyedTokens(t.shadows).map(({ key, value }) => ({
    key,
    value: shadowCss(value),
  }));
  pieces.push(mapOf('shadows', shadows));

  const typo = keyedTokens(t.typography).map(({ key, value }) => {
    const v = typographyCss(value);
    // SCSS maps don't support nested tuple values cleanly; emit a font-shorthand string.
    const lh = v.lineHeight ? `/${v.lineHeight}` : '';
    return { key, value: `("family": ${v.family}, "size": ${v.size}${lh}, "weight": ${v.weight})` };
  });
  pieces.push(mapOf('typography', typo));

  return textArtifact({
    format: 'scss',
    filename: '_tokens.scss',
    contentType: 'text/x-scss',
    text: pieces.filter(Boolean).join('\n'),
  });
}
