/**
 * Storybook stories — one `<Component>.stories.tsx` per detected component.
 * Returned as a ZIP so the whole `stories/` directory lands as a single
 * artifact. Each variant of each component becomes an exported story.
 *
 * If no components were detected (URL-only extractions rarely detect them
 * today), we still emit a placeholder `README.md` explaining why and pointing
 * at the image / PDF input paths that DO populate components.
 */
import JSZip from 'jszip';
import type { Artifact, CanonicalExtraction, Component } from '@prism/shared';
import { bytesArtifact } from './artifact.js';
import { toKebab } from './shared.js';

function toPascalCase(input: string): string {
  return input
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .trim()
    .split(/\s+/)
    .map((w) => (w ? w[0]!.toUpperCase() + w.slice(1).toLowerCase() : ''))
    .join('');
}

function renderStoryFile(component: Component): string {
  const pascalName = toPascalCase(component.name);
  const kebabName = toKebab(component.name);
  const variants =
    component.variants.length > 0
      ? component.variants
      : [{ variantId: 'default', name: 'Default', tokenRefs: {}, confidence: component.confidence }];

  const stories = variants
    .map((variant) => {
      const storyName = toPascalCase(variant.name);
      const args = Object.keys(variant.tokenRefs).length
        ? `\n  args: ${JSON.stringify(variant.tokenRefs, null, 2).replace(/\n/g, '\n  ')},`
        : '';
      return `export const ${storyName}: Story = {${args}\n};`;
    })
    .join('\n\n');

  return `/**
 * Auto-generated by Prism. Component detected with confidence ${component.confidence.toFixed(
    2,
  )}.
 * This file scaffolds Storybook stories for ${pascalName}; wire your real
 * component implementation above.
 */
import type { Meta, StoryObj } from '@storybook/react';

// TODO: replace the placeholder import with your actual component path.
import { ${pascalName} } from '../components/${pascalName}';

const meta: Meta<typeof ${pascalName}> = {
  title: 'Components/${pascalName}',
  component: ${pascalName},
  parameters: { layout: 'padded' },
  tags: ['autodocs', 'prism-scaffold'],
};
export default meta;

type Story = StoryObj<typeof ${pascalName}>;

${stories}
`;
}

function emptyProjectReadme(): string {
  return `# Prism Storybook scaffolds

No components were detected for this extraction. Component detection lives in
the image and PDF vision pipelines — re-run Prism with a screenshot or PDF input
to populate this folder.
`;
}

export async function generateStorybookStories(
  extraction: CanonicalExtraction,
): Promise<Artifact> {
  const zip = new JSZip();
  const stories = zip.folder('stories');
  if (!stories) throw new Error('jszip folder creation failed');

  if (extraction.components.length === 0) {
    stories.file('README.md', emptyProjectReadme());
  } else {
    const nameCounts = new Map<string, number>();
    for (const component of extraction.components) {
      const pascal = toPascalCase(component.name);
      const prior = nameCounts.get(pascal) ?? 0;
      nameCounts.set(pascal, prior + 1);
      const filename = prior === 0 ? `${pascal}.stories.tsx` : `${pascal}${prior + 1}.stories.tsx`;
      stories.file(filename, renderStoryFile(component));
    }
    stories.file(
      'README.md',
      `# Prism Storybook scaffolds\n\n${extraction.components.length} component(s) detected. Story files reference components at \`../components/<Name>\` — implement those or point the import at your existing component library.\n`,
    );
  }

  const bytes = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' });
  return bytesArtifact({
    format: 'storybook-stories',
    filename: 'storybook-stories.zip',
    contentType: 'application/zip',
    bytes,
  });
}
