/**
 * `tailwind.config.ts` — a drop-in Tailwind 3+ config that extends the theme
 * with Prism-extracted colors, spacing, fontSize, fontFamily, borderRadius,
 * and boxShadow. Works with Tailwind v4's config-JS layer too.
 */
import type { Artifact, CanonicalExtraction } from '@prism/shared';
import { textArtifact } from './artifact.js';
import { colorCss, keyedTokens, lengthCss, radiusCss, shadowCss, tokensByCategory, typographyCss } from './shared.js';

function jsObject(entries: { key: string; value: string }[], indent = '        '): string {
  if (entries.length === 0) return '{}';
  const lines = entries.map(({ key, value }) => `${indent}'${key}': ${value},`);
  return `{\n${lines.join('\n')}\n${indent.slice(2)}}`;
}

export function generateTailwindConfig(extraction: CanonicalExtraction): Artifact {
  const t = tokensByCategory(extraction);

  const colors = keyedTokens(t.colors).map(({ key, value }) => ({
    key,
    value: `'${colorCss(value.value)}'`,
  }));
  const spacing = keyedTokens(t.spacing).map(({ key, value }) => ({
    key,
    value: `'${lengthCss(value.value)}'`,
  }));
  const radii = keyedTokens(t.radii).map(({ key, value }) => ({
    key,
    value: `'${radiusCss(value)}'`,
  }));
  const shadows = keyedTokens(t.shadows).map(({ key, value }) => ({
    key,
    value: `'${shadowCss(value).replace(/'/g, "\\'")}'`,
  }));

  // fontSize entries: [size, { lineHeight, letterSpacing, fontWeight }]
  const fontSize = keyedTokens(t.typography).map(({ key, value }) => {
    const v = typographyCss(value);
    const extras: string[] = [];
    if (v.lineHeight !== undefined) extras.push(`lineHeight: '${v.lineHeight}'`);
    if (v.letterSpacing !== undefined) extras.push(`letterSpacing: '${v.letterSpacing}'`);
    extras.push(`fontWeight: ${v.weight}`);
    return {
      key,
      value: `['${v.size}', { ${extras.join(', ')} }]`,
    };
  });

  // Distinct font families (one entry per unique family stack).
  const seenFamilies = new Set<string>();
  const fontFamily: { key: string; value: string }[] = [];
  for (const { key, value } of keyedTokens(t.typography)) {
    const v = typographyCss(value);
    if (seenFamilies.has(v.family)) continue;
    seenFamilies.add(v.family);
    const arr = v.family
      .split(',')
      .map((s) => s.trim().replace(/^['"]|['"]$/g, ''))
      .map((s) => `'${s.replace(/'/g, "\\'")}'`);
    fontFamily.push({ key, value: `[${arr.join(', ')}]` });
  }

  const text = [
    `/* Generated by Prism — https://github.com/REPLACE_ME/prism */`,
    `/* Extraction ${extraction.extractionId} · ${extraction.tokens.length} tokens */`,
    `import type { Config } from 'tailwindcss';`,
    ``,
    `export default {`,
    `  content: ['./src/**/*.{ts,tsx,js,jsx,html}'],`,
    `  theme: {`,
    `    extend: {`,
    `      colors: ${jsObject(colors)},`,
    `      spacing: ${jsObject(spacing)},`,
    `      borderRadius: ${jsObject(radii)},`,
    `      boxShadow: ${jsObject(shadows)},`,
    `      fontSize: ${jsObject(fontSize)},`,
    `      fontFamily: ${jsObject(fontFamily)},`,
    `    },`,
    `  },`,
    `  plugins: [],`,
    `} satisfies Config;`,
    ``,
  ].join('\n');

  return textArtifact({
    format: 'tailwind-config',
    filename: 'tailwind.config.ts',
    contentType: 'application/typescript',
    text,
  });
}
